/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as MensagensRapidasRouteImport } from './routes/mensagens-rapidas'
import { Route as HorariosRouteImport } from './routes/horarios'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContatosRouteImport } from './routes/contatos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AutomacaoIaRouteImport } from './routes/automacao-ia'
import { Route as AtendimentosRouteImport } from './routes/atendimentos'
import { Route as AtendentesRouteImport } from './routes/atendentes'
import { Route as IndexRouteImport } from './routes/index'

const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRapidasRoute = MensagensRapidasRouteImport.update({
  id: '/mensagens-rapidas',
  path: '/mensagens-rapidas',
  getParentRoute: () => rootRouteImport,
} as any)
const HorariosRoute = HorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatosRoute = ContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacaoIaRoute = AutomacaoIaRouteImport.update({
  id: '/automacao-ia',
  path: '/automacao-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentosRoute = AtendimentosRouteImport.update({
  id: '/atendimentos',
  path: '/atendimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendentesRoute = AtendentesRouteImport.update({
  id: '/atendentes',
  path: '/atendentes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atendentes': typeof AtendentesRoute
  '/atendimentos': typeof AtendimentosRoute
  '/automacao-ia': typeof AutomacaoIaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contatos': typeof ContatosRoute
  '/dashboard': typeof DashboardRoute
  '/horarios': typeof HorariosRoute
  '/mensagens-rapidas': typeof MensagensRapidasRoute
  '/tags': typeof TagsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atendentes': typeof AtendentesRoute
  '/atendimentos': typeof AtendimentosRoute
  '/automacao-ia': typeof AutomacaoIaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contatos': typeof ContatosRoute
  '/dashboard': typeof DashboardRoute
  '/horarios': typeof HorariosRoute
  '/mensagens-rapidas': typeof MensagensRapidasRoute
  '/tags': typeof TagsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atendentes': typeof AtendentesRoute
  '/atendimentos': typeof AtendimentosRoute
  '/automacao-ia': typeof AutomacaoIaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contatos': typeof ContatosRoute
  '/dashboard': typeof DashboardRoute
  '/horarios': typeof HorariosRoute
  '/mensagens-rapidas': typeof MensagensRapidasRoute
  '/tags': typeof TagsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atendentes'
    | '/atendimentos'
    | '/automacao-ia'
    | '/configuracoes'
    | '/contatos'
    | '/dashboard'
    | '/horarios'
    | '/mensagens-rapidas'
    | '/tags'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atendentes'
    | '/atendimentos'
    | '/automacao-ia'
    | '/configuracoes'
    | '/contatos'
    | '/dashboard'
    | '/horarios'
    | '/mensagens-rapidas'
    | '/tags'
  id:
    | '__root__'
    | '/'
    | '/atendentes'
    | '/atendimentos'
    | '/automacao-ia'
    | '/configuracoes'
    | '/contatos'
    | '/dashboard'
    | '/horarios'
    | '/mensagens-rapidas'
    | '/tags'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtendentesRoute: typeof AtendentesRoute
  AtendimentosRoute: typeof AtendimentosRoute
  AutomacaoIaRoute: typeof AutomacaoIaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContatosRoute: typeof ContatosRoute
  DashboardRoute: typeof DashboardRoute
  HorariosRoute: typeof HorariosRoute
  MensagensRapidasRoute: typeof MensagensRapidasRoute
  TagsRoute: typeof TagsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens-rapidas': {
      id: '/mensagens-rapidas'
      path: '/mensagens-rapidas'
      fullPath: '/mensagens-rapidas'
      preLoaderRoute: typeof MensagensRapidasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horarios': {
      id: '/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof HorariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatos': {
      id: '/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof ContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacao-ia': {
      id: '/automacao-ia'
      path: '/automacao-ia'
      fullPath: '/automacao-ia'
      preLoaderRoute: typeof AutomacaoIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimentos': {
      id: '/atendimentos'
      path: '/atendimentos'
      fullPath: '/atendimentos'
      preLoaderRoute: typeof AtendimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendentes': {
      id: '/atendentes'
      path: '/atendentes'
      fullPath: '/atendentes'
      preLoaderRoute: typeof AtendentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtendentesRoute: AtendentesRoute,
  AtendimentosRoute: AtendimentosRoute,
  AutomacaoIaRoute: AutomacaoIaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContatosRoute: ContatosRoute,
  DashboardRoute: DashboardRoute,
  HorariosRoute: HorariosRoute,
  MensagensRapidasRoute: MensagensRapidasRoute,
  TagsRoute: TagsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
